project_id = "zkwcbyxiwklihegjhuql"

[functions.ai-chat]
enabled = true
verify_jwt = false

[functions.ai-optimize-route]
enabled = true
verify_jwt = false

[functions.google-directions]
enabled = true
verify_jwt = false

[functions.ai-suggest-collections]
enabled = true
verify_jwt = false
